# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/jarvis',
                'doc_host': 'https://matdmiller.github.io',
                'git_url': 'https://github.com/matdmiller/jarvis',
                'lib_path': 'jarvis'},
  'syms': {'jarvis.core': {'jarvis.core.foo': ('core.html#foo', 'jarvis/core.py')}}}
