# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_basic_chat_gradio.ipynb.

# %% auto 0
__all__ = ['parse_codeblock', 'gradio_chat_history_to_openai_chat_completions_format', 'process_user_message',
           'process_bot_message']

# %% ../nbs/02_basic_chat_gradio.ipynb 4
import jarvis.secrets

# %% ../nbs/02_basic_chat_gradio.ipynb 5
import openai
import numpy as np
import os
import json
import gradio as gr
import datetime

# %% ../nbs/02_basic_chat_gradio.ipynb 21
def parse_codeblock(text):
    """Fixes how code blocks are displayed in the gradio chat window. 
    Ref: https://github.com/gradio-app/gradio/issues/3531"""
    lines = text.split("\n")
    for i, line in enumerate(lines):
        if "```" in line:
            if line != "```":
                lines[i] = f'<pre><code class="{lines[i][3:]}">'
            else:
                lines[i] = '</code></pre>'
        else:
            if i > 0:
                lines[i] = "<br/>" + line.replace("<", "&lt;").replace(">", "&gt;")
    return "".join(lines)

# %% ../nbs/02_basic_chat_gradio.ipynb 23
def gradio_chat_history_to_openai_chat_completions_format(
    history:list[list[dict]] #Gradio chat history.
)->list[dict]:
    """Converts gradio chat history to OpenAI messages completions format."""
    chat_formatted_list = []
    for message_pair in history:
        chat_formatted_list.append({'role':'user', 'content': message_pair[0]})
        if message_pair[1] is not None:
            chat_formatted_list.append({'role':'assistant', 'content': message_pair[1]})
    return chat_formatted_list

# %% ../nbs/02_basic_chat_gradio.ipynb 24
def process_user_message(
    user_message:str, #Most recent message from user.
    history:list[list[str]] #Message history from gradio.Chatbot instance.
)->tuple[str,list[list[str]]]:
    """Add user message to 'history' and clear message textbox."""
    print('process_user_message',user_message,history)
    # if history is None: history = []
    return "", history + [[user_message, None]]

# %% ../nbs/02_basic_chat_gradio.ipynb 25
def process_bot_message(
    history:list[list[str]], #Message history from gradio.Chatbot instance.
    system_msg:str, #Most recent message from user.
    selected_model:str, #Selected OpenAI model for chat completion.
    temperature:float=0., #How deterministic the model results are.  See OpenAI docs.
    stream:bool=True, #Whether or not to stream the results or return all at once when the model has finished its response.
)->list[list[str]]:
    """Send chat history with most recent user message to the chat completions API."""
    stream_results = ''
    history[-1][1] = ''
    # try:
    response = openai.ChatCompletion.create(
        model=selected_model,
        messages=[{'role':'system', 'content': system_msg}] + gradio_chat_history_to_openai_chat_completions_format(history),
        temperature=temperature,
        stream=stream  # this time, we set stream=True
    )
    if stream:
        for chunk in response:
            model_results.append(model_results)
            # print(chunk)
            # print(chunk.get('choices',[{}])[0].get('delta',{}).get('content',''),end='')
            stream_results += chunk.get('choices',[{}])[0].get('delta',{}).get('content','')
            # history[-1][1] = parse_codeblock(stream_results) #removed because gradio properly formats code blocks now
            history[-1][1] = stream_results
            yield history
    else:
        # print(response)
        # print(response.get('choices',[{}])[0].get('message',{}).get('content',''))
        # print(parse_codeblock(response.get('choices',[{}])[0].get('message',{}).get('content','')))
        # history[-1][1] = parse_codeblock(response.get('choices',[{}])[0].get('message',{}).get('content','')) #gradio fixed code blocks natively
        history[-1][1] = response.get('choices',[{}])[0].get('message',{}).get('content','')
        # print(history)
        yield history
    # except:
    #     pass
    #     # print(history, system_msg, [{'role':'system', 'content': system_msg}] + history_to_chatgpt_format(history))

    # print(response)
    # print(stream_results)
    # print(parse_codeblock(stream_results))
    # print(history[-1][1])
