# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/12_openai_embeddings.ipynb.

# %% auto 0
__all__ = ['PINECONE_API_KEY', 'PINECONE_ENV', 'PINECONE_TEST_NAMESPACE', 'OPENAI_API_KEY', 'foo']

# %% ../nbs/12_openai_embeddings.ipynb 4
import os
try:
    import jarvis.jarvis_secrets
except:
    pass

# %% ../nbs/12_openai_embeddings.ipynb 5
PINECONE_API_KEY = os.environ["PINECONE_API_KEY"]
PINECONE_ENV = os.environ["PINECONE_ENV"]
PINECONE_TEST_NAMESPACE = os.environ["PINECONE_TEST_NAMESPACE"]
OPENAI_API_KEY = os.environ["OPENAI_API_KEY"]

# %% ../nbs/12_openai_embeddings.ipynb 7
def foo(): pass
