# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/11_pinecone.ipynb.

# %% auto 0
__all__ = ['PINECONE_API_KEY', 'PINECONE_ENV', 'PINECONE_TEST_NAMESPACE', 'OPENAI_API_KEY', 'foo']

# %% ../nbs/11_pinecone.ipynb 4
def foo(): pass

# %% ../nbs/11_pinecone.ipynb 5
import os
try:
    import jarvis.jarvis_secrets
except:
    pass

# %% ../nbs/11_pinecone.ipynb 6
PINECONE_API_KEY = os.environ["PINECONE_API_KEY"]
PINECONE_ENV = os.environ["PINECONE_ENV"]
PINECONE_TEST_NAMESPACE = os.environ["PINECONE_TEST_NAMESPACE"]
OPENAI_API_KEY = os.environ["OPENAI_API_KEY"]
